# Generated by Django 6.0.6 on 2026-07-09 07:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AssetCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "custom_fields_schema",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Kategoriye özel alan şeması. Örn: laptop için cpu/ram/disk, yazıcı için toner_model/connection_type.",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Varlık Kategorisi",
                "verbose_name_plural": "Varlık Kategorileri",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Örn: Bilgi İşlem Laptop 01, Muhasebe Yazıcı 02.",
                        max_length=180,
                    ),
                ),
                ("brand", models.CharField(blank=True, max_length=120)),
                ("model", models.CharField(blank=True, max_length=120)),
                (
                    "serial_number",
                    models.CharField(
                        blank=True,
                        help_text="Üretici seri numarası. Boş bırakılabilir ama varsa benzersiz olmalı.",
                        max_length=150,
                        null=True,
                    ),
                ),
                (
                    "inventory_code",
                    models.CharField(
                        blank=True,
                        help_text="Şirket içi envanter kodu. Örn: IT-LPT-0001.",
                        max_length=80,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Aktif"),
                            ("assigned", "Zimmetli"),
                            ("in_stock", "Depoda / Boşta"),
                            ("in_repair", "Bakımda / Onarımda"),
                            ("faulty", "Arızalı"),
                            ("retired", "Emekli"),
                            ("disposed", "İmha Edildi"),
                            ("lost", "Kayıp"),
                        ],
                        default="active",
                        max_length=30,
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="Örn: Genel Müdürlük, Depo, Mağaza 1, Bilgi İşlem Odası.",
                        max_length=180,
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="Yazıcı, sunucu, switch gibi ağ cihazları için.",
                        null=True,
                    ),
                ),
                (
                    "mac_address",
                    models.CharField(
                        blank=True, help_text="Opsiyonel MAC adresi.", max_length=50
                    ),
                ),
                ("purchase_date", models.DateField(blank=True, null=True)),
                (
                    "purchase_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "vendor_name",
                    models.CharField(
                        blank=True,
                        help_text="Tedarikçi adı. İleride Vendor tablosuna bağlanabilir.",
                        max_length=180,
                    ),
                ),
                (
                    "warranty_end_date",
                    models.DateField(
                        blank=True,
                        help_text="Garanti bitiş tarihi. Reminder motoru buradan uyarı üretecek.",
                        null=True,
                    ),
                ),
                (
                    "maintenance_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Bu varlık için periyodik bakım takibi aktif mi?",
                    ),
                ),
                (
                    "maintenance_frequency_days",
                    models.PositiveIntegerField(
                        blank=True, help_text="Bakım sıklığı. Örn: 90 gün.", null=True
                    ),
                ),
                (
                    "next_maintenance_due_date",
                    models.DateField(
                        blank=True,
                        help_text="Sonraki bakım tarihi. Dashboard ve reminder için kullanılır.",
                        null=True,
                    ),
                ),
                (
                    "custom_fields",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Kategoriye özel esnek bilgiler. Örn: cpu, ram, disk, toner_model.",
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_assets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_assets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assets",
                        to="inventory.assetcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Varlık",
                "verbose_name_plural": "Varlıklar",
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["name"], name="inventory_a_name_bfaf8b_idx"),
                    models.Index(
                        fields=["status"], name="inventory_a_status_69dd7e_idx"
                    ),
                    models.Index(
                        fields=["category"], name="inventory_a_categor_4ca7a3_idx"
                    ),
                    models.Index(
                        fields=["serial_number"], name="inventory_a_serial__4865f1_idx"
                    ),
                    models.Index(
                        fields=["inventory_code"], name="inventory_a_invento_d0b1f3_idx"
                    ),
                    models.Index(
                        fields=["warranty_end_date"],
                        name="inventory_a_warrant_267721_idx",
                    ),
                    models.Index(
                        fields=["next_maintenance_due_date"],
                        name="inventory_a_next_ma_42e7dd_idx",
                    ),
                    models.Index(
                        fields=["is_deleted"], name="inventory_a_is_dele_0fe925_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("serial_number__isnull", False),
                            models.Q(("serial_number", ""), _negated=True),
                        ),
                        fields=("serial_number",),
                        name="unique_non_empty_asset_serial_number",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("inventory_code__isnull", False),
                            models.Q(("inventory_code", ""), _negated=True),
                        ),
                        fields=("inventory_code",),
                        name="unique_non_empty_asset_inventory_code",
                    ),
                ],
            },
        ),
    ]
