# Generated by Django 6.0.6 on 2026-07-13 08:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="asset",
            name="unique_non_empty_asset_serial_number",
        ),
        migrations.RemoveConstraint(
            model_name="asset",
            name="unique_non_empty_asset_inventory_code",
        ),
        migrations.AddConstraint(
            model_name="asset",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("is_deleted", False),
                    ("serial_number__isnull", False),
                    models.Q(("serial_number", ""), _negated=True),
                ),
                fields=("serial_number",),
                name="unique_active_asset_serial_number",
            ),
        ),
        migrations.AddConstraint(
            model_name="asset",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("is_deleted", False),
                    ("inventory_code__isnull", False),
                    models.Q(("inventory_code", ""), _negated=True),
                ),
                fields=("inventory_code",),
                name="unique_active_asset_inventory_code",
            ),
        ),
    ]
