# Generated by Django 6.0.6 on 2026-07-09 09:19

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inventory", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LicenseSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Örn: Microsoft 365 Business Premium, Adobe Creative Cloud.",
                        max_length=180,
                    ),
                ),
                (
                    "tracking_code",
                    models.CharField(
                        blank=True,
                        help_text="Şirket içi lisans/abonelik takip kodu. Örn: LIC-M365-001.",
                        max_length=80,
                        null=True,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("license", "Lisans"), ("subscription", "Abonelik")],
                        default="subscription",
                        max_length=30,
                    ),
                ),
                (
                    "vendor",
                    models.CharField(
                        blank=True,
                        help_text="Tedarikçi/üretici. Örn: Microsoft, Adobe, ESET.",
                        max_length=180,
                    ),
                ),
                (
                    "license_key_masked",
                    models.CharField(
                        blank=True,
                        help_text="Tam lisans anahtarı tutulmaz. Sadece maskeli değer girilir. Örn: XXXX-XXXX-1234.",
                        max_length=120,
                    ),
                ),
                (
                    "seat_count",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        help_text="Bitiş/yenileme tarihi. Reminder motoru buradan uyarı üretecek.",
                        null=True,
                    ),
                ),
                (
                    "renewal_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "billing_cycle",
                    models.CharField(
                        choices=[
                            ("one_time", "Tek Seferlik"),
                            ("monthly", "Aylık"),
                            ("yearly", "Yıllık"),
                            ("other", "Diğer"),
                        ],
                        default="yearly",
                        max_length=30,
                    ),
                ),
                (
                    "auto_renew",
                    models.BooleanField(
                        default=False, help_text="Otomatik yenileniyor mu?"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "assigned_asset",
                    models.ForeignKey(
                        blank=True,
                        help_text="Bu lisans belirli bir cihaza bağlıysa seçilir.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="license_subscriptions",
                        to="inventory.asset",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_license_subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_license_subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Lisans / Abonelik",
                "verbose_name_plural": "Lisanslar / Abonelikler",
                "ordering": ["end_date", "name"],
                "indexes": [
                    models.Index(fields=["name"], name="licensing_l_name_91fd81_idx"),
                    models.Index(fields=["type"], name="licensing_l_type_cb95c7_idx"),
                    models.Index(
                        fields=["vendor"], name="licensing_l_vendor_d85013_idx"
                    ),
                    models.Index(
                        fields=["end_date"], name="licensing_l_end_dat_c2e5ca_idx"
                    ),
                    models.Index(
                        fields=["is_active"], name="licensing_l_is_acti_35d526_idx"
                    ),
                    models.Index(
                        fields=["is_deleted"], name="licensing_l_is_dele_fe83d0_idx"
                    ),
                    models.Index(
                        fields=["assigned_asset"], name="licensing_l_assigne_45866c_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("tracking_code__isnull", False),
                            models.Q(("tracking_code", ""), _negated=True),
                        ),
                        fields=("tracking_code",),
                        name="unique_non_empty_license_tracking_code",
                    )
                ],
            },
        ),
    ]
