# Generated by Django 6.0.6 on 2026-07-09 09:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Reminder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("warranty", "Garanti"),
                            ("maintenance", "Bakım"),
                            ("license", "Lisans / Abonelik"),
                            ("ticket_sla", "Ticket SLA"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "source_id",
                    models.PositiveIntegerField(
                        help_text="Kaynak kaydın ID değeri. Örn: Asset ID veya LicenseSubscription ID."
                    ),
                ),
                ("title", models.CharField(max_length=220)),
                ("message", models.TextField()),
                (
                    "due_date",
                    models.DateField(
                        help_text="Asıl olay tarihi. Örn: garanti bitiş, bakım tarihi, lisans bitiş tarihi."
                    ),
                ),
                (
                    "threshold_days",
                    models.PositiveIntegerField(
                        help_text="Kaç gün kala uyarı üretileceği. Örn: 30, 15, 7, 1."
                    ),
                ),
                (
                    "scheduled_for",
                    models.DateField(
                        help_text="Reminder'ın görünür/işlenebilir olacağı tarih. due_date - threshold_days."
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[("in_app", "Uygulama İçi"), ("email", "E-posta")],
                        default="in_app",
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Bekliyor"),
                            ("sent", "Gönderildi"),
                            ("dismissed", "Gizlendi"),
                            ("cancelled", "İptal Edildi"),
                        ],
                        default="pending",
                        max_length=30,
                    ),
                ),
                ("notified_at", models.DateTimeField(blank=True, null=True)),
                ("dismissed_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Kaynak hakkında snapshot bilgi. Örn: asset_code, license_vendor.",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_reminders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Hatırlatıcı",
                "verbose_name_plural": "Hatırlatıcılar",
                "ordering": ["scheduled_for", "due_date", "threshold_days"],
                "indexes": [
                    models.Index(
                        fields=["source_type"], name="reminders_r_source__32b0b6_idx"
                    ),
                    models.Index(
                        fields=["source_id"], name="reminders_r_source__d19234_idx"
                    ),
                    models.Index(
                        fields=["due_date"], name="reminders_r_due_dat_002496_idx"
                    ),
                    models.Index(
                        fields=["scheduled_for"], name="reminders_r_schedul_d3d10e_idx"
                    ),
                    models.Index(
                        fields=["threshold_days"], name="reminders_r_thresho_30aa9f_idx"
                    ),
                    models.Index(
                        fields=["channel"], name="reminders_r_channel_d8a6a4_idx"
                    ),
                    models.Index(
                        fields=["status"], name="reminders_r_status_c60465_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status", "cancelled"), _negated=True),
                        fields=(
                            "source_type",
                            "source_id",
                            "due_date",
                            "threshold_days",
                            "channel",
                        ),
                        name="unique_active_reminder_per_source_due_threshold_channel",
                    )
                ],
            },
        ),
    ]
