# Generated by Django 6.0.6 on 2026-07-14 11:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='snoozed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reminder',
            name='snoozed_until',
            field=models.DateField(blank=True, help_text='Bugün gizle gibi geçici erteleme tarihi. Bu tarih geçince pending reminder tekrar görünür.', null=True),
        ),
        migrations.AddIndex(
            model_name='reminder',
            index=models.Index(fields=['snoozed_until'], name='reminders_r_snoozed_fe8eac_idx'),
        ),
    ]
