# Generated by Django 6.0.6 on 2026-07-12 19:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Oluşturma"),
                            ("update", "Güncelleme"),
                            ("delete", "Silme"),
                            ("restore", "Geri Alma"),
                            ("assign", "Zimmetleme"),
                            ("return", "İade Alma"),
                            ("dispose", "İmha"),
                            ("status_change", "Durum Değişikliği"),
                            ("login", "Giriş"),
                            ("logout", "Çıkış"),
                            ("other", "Diğer"),
                        ],
                        db_index=True,
                        max_length=32,
                        verbose_name="İşlem",
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        db_index=True,
                        help_text="Örn: inventory.Asset, assignments.Assignment, maintenance.MaintenanceRecord",
                        max_length=120,
                        verbose_name="Varlık Tipi",
                    ),
                ),
                (
                    "entity_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=64,
                        verbose_name="Varlık ID",
                    ),
                ),
                (
                    "entity_repr",
                    models.CharField(
                        blank=True,
                        help_text="Log ekranında okunabilir kısa temsil.",
                        max_length=255,
                        verbose_name="Varlık Görünümü",
                    ),
                ),
                (
                    "before",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Önceki Veri"
                    ),
                ),
                (
                    "after",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Sonraki Veri"
                    ),
                ),
                (
                    "changes",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Sadece değişen alanlar.",
                        verbose_name="Değişiklikler",
                    ),
                ),
                (
                    "request_method",
                    models.CharField(
                        blank=True, max_length=16, verbose_name="HTTP Metodu"
                    ),
                ),
                (
                    "request_path",
                    models.CharField(
                        blank=True, max_length=512, verbose_name="İstek Yolu"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP Adresi"
                    ),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="User Agent")),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Ek Metadata"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        verbose_name="Oluşturulma Tarihi",
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="İşlemi Yapan Kullanıcı",
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Log",
                "verbose_name_plural": "Audit Logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["entity_type", "entity_id"],
                        name="audit_audit_entity__9535bf_idx",
                    ),
                    models.Index(
                        fields=["action", "created_at"],
                        name="audit_audit_action_766c6d_idx",
                    ),
                    models.Index(
                        fields=["actor", "created_at"],
                        name="audit_audit_actor_i_ec0f72_idx",
                    ),
                ],
            },
        ),
    ]
