# Generated by Django 6.0.6 on 2026-07-16 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Oluşturma'), ('update', 'Güncelleme'), ('delete', 'Silme'), ('restore', 'Geri Alma'), ('assign', 'Zimmetleme'), ('return', 'İade Alma'), ('dispose', 'İmha'), ('status_change', 'Durum Değişikliği'), ('export', 'Dışa Aktarma'), ('login', 'Giriş'), ('logout', 'Çıkış'), ('other', 'Diğer')], db_index=True, max_length=32, verbose_name='İşlem'),
        ),
    ]
