# Generated by Django 6.0.6 on 2026-07-09 08:53

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inventory", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MaintenanceRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("maintenance", "Bakım"),
                            ("repair", "Onarım"),
                            ("disposal", "İmha"),
                        ],
                        default="maintenance",
                        max_length=30,
                    ),
                ),
                (
                    "performed_at",
                    models.DateField(
                        default=django.utils.timezone.localdate,
                        help_text="Bakım/onarım/imha işleminin yapıldığı tarih.",
                    ),
                ),
                (
                    "next_due_date",
                    models.DateField(
                        blank=True,
                        help_text="Bir sonraki bakım tarihi. Reminder motoru buradan uyarı üretecek.",
                        null=True,
                    ),
                ),
                (
                    "frequency_days",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Periyodik bakım sıklığı. Örn: 90 gün.",
                        null=True,
                    ),
                ),
                (
                    "cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "performed_by",
                    models.CharField(
                        blank=True,
                        help_text="İşlemi yapan kişi/firma. Örn: Bilgi İşlem, Servis Firması.",
                        max_length=180,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "asset_status_before",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("active", "Aktif"),
                            ("assigned", "Zimmetli"),
                            ("in_stock", "Depoda / Boşta"),
                            ("in_repair", "Bakımda / Onarımda"),
                            ("faulty", "Arızalı"),
                            ("retired", "Emekli"),
                            ("disposed", "İmha Edildi"),
                            ("lost", "Kayıp"),
                        ],
                        help_text="İşlem öncesi varlık durumu. Sistem tarafından doldurulur.",
                        max_length=30,
                    ),
                ),
                (
                    "asset_status_after",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("active", "Aktif"),
                            ("assigned", "Zimmetli"),
                            ("in_stock", "Depoda / Boşta"),
                            ("in_repair", "Bakımda / Onarımda"),
                            ("faulty", "Arızalı"),
                            ("retired", "Emekli"),
                            ("disposed", "İmha Edildi"),
                            ("lost", "Kayıp"),
                        ],
                        help_text="İşlem sonrası varlık durumu. Boş bırakılırsa tipe göre sistem makul varsayılan uygular.",
                        max_length=30,
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="maintenance_records",
                        to="inventory.asset",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_maintenance_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_maintenance_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Bakım / Onarım Kaydı",
                "verbose_name_plural": "Bakım / Onarım Kayıtları",
                "ordering": ["-performed_at", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["asset"], name="maintenance_asset_i_66ae58_idx"
                    ),
                    models.Index(fields=["type"], name="maintenance_type_2a45be_idx"),
                    models.Index(
                        fields=["performed_at"], name="maintenance_perform_f3fd35_idx"
                    ),
                    models.Index(
                        fields=["next_due_date"], name="maintenance_next_du_c44a90_idx"
                    ),
                    models.Index(
                        fields=["created_by"], name="maintenance_created_98ae15_idx"
                    ),
                ],
            },
        ),
    ]
