# Generated by Django 6.0.6 on 2026-07-14 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('technician', 'Technician'), ('viewer', 'Viewer'), ('approver', 'Approver'), ('requester', 'Requester')], default='technician', max_length=20),
        ),
    ]
