# Generated by Django 6.0.6 on 2026-07-14 05:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='external_hr_id',
            field=models.CharField(blank=True, help_text='İleride HR sistemiyle eşleşme için harici personel ID.', max_length=120),
        ),
        migrations.AddField(
            model_name='employee',
            name='manager',
            field=models.ForeignKey(blank=True, help_text='Personelin bağlı olduğu amir/yönetici.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_reports', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='employee',
            name='sync_source',
            field=models.CharField(choices=[('manual', 'Manual'), ('excel', 'Excel'), ('hr_api', 'HR API')], default='manual', help_text='Personel kaydının ana kaynağı.', max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Bu personelle eşleşen sistem kullanıcısı.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['external_hr_id'], name='employees_e_externa_11cad7_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['sync_source'], name='employees_e_sync_so_592fad_idx'),
        ),
    ]
