# Generated by Django 6.0.6 on 2026-07-14 08:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_external_hr_id_employee_manager_and_more'),
        ('tickets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Onay bekliyor'), ('approved', 'Onaylandı'), ('rejected', 'Reddedildi')], default='pending', max_length=30)),
                ('decision_note', models.TextField(blank=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approver', models.ForeignKey(help_text='Talebi onaylayacak yönetici/personel.', on_delete=django.db.models.deletion.PROTECT, related_name='ticket_approvals', to='employees.employee')),
                ('approver_user', models.ForeignKey(blank=True, help_text='Onayı verecek sistem kullanıcısı.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_approvals_to_decide', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_approvals_requested', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='tickets.ticket')),
            ],
            options={
                'verbose_name': 'Ticket Onayı',
                'verbose_name_plural': 'Ticket Onayları',
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['status'], name='tickets_tic_status_30174d_idx'), models.Index(fields=['approver_user', 'status'], name='tickets_tic_approve_d4dcf0_idx'), models.Index(fields=['ticket', 'status'], name='tickets_tic_ticket__e5fbd9_idx'), models.Index(fields=['requested_at'], name='tickets_tic_request_d7824d_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('ticket', 'approver_user'), name='unique_pending_approval_per_ticket_approver')],
            },
        ),
    ]
