# Generated by Django 6.0.6 on 2026-07-16 12:23

import apps.tickets.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticketapproval'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=apps.tickets.models.ticket_attachment_upload_to)),
                ('original_filename', models.CharField(max_length=255)),
                ('mime_type', models.CharField(max_length=120)),
                ('size_bytes', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='tickets.ticket')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ticket Eki',
                'verbose_name_plural': 'Ticket Ekleri',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['ticket', 'uploaded_at'], name='tickets_tic_ticket__03c957_idx'), models.Index(fields=['uploaded_by', 'uploaded_at'], name='tickets_tic_uploade_864636_idx'), models.Index(fields=['mime_type'], name='tickets_tic_mime_ty_ff8c2e_idx')],
            },
        ),
    ]
