# Generated by Django 6.0.6 on 2026-07-20 07:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_ticket_closed_by_ticket_resolution_note_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('open', 'Açık'), ('in_progress', 'İşlemde'), ('returned_to_requester', 'Talep sahibine geri gönderildi'), ('resolved', 'Çözüldü'), ('closed', 'Kapandı')], default='open', max_length=30),
        ),
        migrations.CreateModel(
            name='TicketITDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('returned', 'Geri Çevrildi')], default='returned', max_length=30)),
                ('comment', models.TextField()),
                ('decided_at', models.DateTimeField(auto_now_add=True)),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ticket_it_decisions', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='it_decisions', to='tickets.ticket')),
            ],
            options={
                'verbose_name': 'Ticket IT Kararı',
                'verbose_name_plural': 'Ticket IT Kararları',
                'ordering': ['-decided_at'],
                'indexes': [models.Index(fields=['ticket', 'decided_at'], name='tickets_tic_ticket__a42ed5_idx'), models.Index(fields=['technician', 'decided_at'], name='tickets_tic_technic_9d07bb_idx'), models.Index(fields=['decision'], name='tickets_tic_decisio_9a5ad4_idx')],
            },
        ),
    ]
